### ISSUE TITLE
Make file error ?

### ISSUE THREAD

**Issue by Sudarshanshetty** [NateRickard/Google-Maps-Utils-Binding#1]
On doing  :-  To build, run `make` in the `extern` directory.
EMACBOOK-49:~ sudarshan.shetty$ cd /Users/sudarshan.shetty/Downloads/Google-Maps-Utils-Binding-master/GoogleMapsUtils.iOS/extern 
EMACBOOK-49:extern sudarshan.shetty$ make
rm -rf ios
mkdir -p ios
cd ios && git clone git@github.com:googlemaps/google-maps-ios-utils.git
Cloning into 'google-maps-ios-utils'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
make: **\* [Podfile.lock] Error 128

Can you please tell what could be the problem ?

**Comment by Sudarshanshetty** [comment]
After adding SSH key , issue got solved

**Comment by tahmidmozaffar** [comment]
Hello, @Sudarshanshetty, I am having problem generating the googlemaputil.dll. Have you succeeded with this? Is your dll is available somewhere that I can download it from?

**Comment by Sudarshanshetty** [comment]
@receme : Yes i was able to implement the google map clustering with above binding project. Can you please tell what is the problem your facing with screenshot

**Comment by tahmidmozaffar** [comment]
As instructed, I clone the project, then Run the Makefile in extern directory. Here what I got in the terminal.

> IOS_GIT_BRANCH=master
> XBUILD=/Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild
> WORKSPACE=GoogleMapsUtils.xcworkspace
> WORKSPACE_DIR=ios/google-maps-ios-utils/workspace
> SCHEME=GoogleMapsUtils
> SCHEME_FILE=GoogleMapsUtils.xcscheme
> SCHEME_DIR=GoogleMapsUtils.xcworkspace/xcshareddata/xcschemes
> BUILD_ROOT=build/Build/Products
> VALID_ARCHS="armv7 armv7s arm64 i386 x86_64"
> 
> all: clean libGoogleMapsUtils.a
> 
> Podfile.lock:
>     mkdir -p ios
>     cd ios && git clone git@github.com:googlemaps/google-maps-ios-utils.git
>     cd ios/google-maps-ios-utils && git checkout $(IOS_GIT_BRANCH)
>     cd $(WORKSPACE_DIR) && pod install
>     mkdir -p $(WORKSPACE_DIR)/$(SCHEME_DIR) && cp $(SCHEME_FILE) $(WORKSPACE_DIR)/$(SCHEME_DIR)
> 
> libGoogleMapsUtils-i386.a: Podfile.lock
>     cd $(WORKSPACE_DIR) && $(XBUILD) -workspace $(WORKSPACE) -scheme $(SCHEME) -sdk iphonesimulator -arch i386 -configuration Release VALID_ARCHS=$(VALID_ARCHS) ONLY_ACTIVE_ARCH=NO EFFECTIVE_PLATFORM_NAME="-iphonesimulator" -derivedDataPath build clean build  
>     mv $(WORKSPACE_DIR)/$(BUILD_ROOT)/Release-iphonesimulator/libGoogleMapsUtils.a $@
> 
> libGoogleMapsUtils-x86_64.a: Podfile.lock
>     cd $(WORKSPACE_DIR) && $(XBUILD) -workspace $(WORKSPACE) -scheme $(SCHEME) -sdk iphonesimulator -arch x86_64 -configuration Release VALID_ARCHS=$(VALID_ARCHS) ONLY_ACTIVE_ARCH=NO EFFECTIVE_PLATFORM_NAME="-iphonesimulator" -derivedDataPath build clean build
>     mv $(WORKSPACE_DIR)/$(BUILD_ROOT)/Release-iphonesimulator/libGoogleMapsUtils.a $@
> 
> libGoogleMapsUtils-armv7.a: Podfile.lock
>     cd $(WORKSPACE_DIR) && $(XBUILD) -workspace $(WORKSPACE) -scheme $(SCHEME) -sdk iphoneos -arch armv7 -configuration Release -derivedDataPath build clean build
>     mv $(WORKSPACE_DIR)/$(BUILD_ROOT)/Release-iphoneos/libGoogleMapsUtils.a $@
> 
> libGoogleMapsUtils-arm64.a: Podfile.lock
>     cd $(WORKSPACE_DIR) && $(XBUILD) -workspace $(WORKSPACE) -scheme $(SCHEME) -sdk iphoneos -arch arm64 -configuration Release -derivedDataPath build clean build
>     mv $(WORKSPACE_DIR)/$(BUILD_ROOT)/Release-iphoneos/libGoogleMapsUtils.a $@
> 
> libGoogleMapsUtils.a: libGoogleMapsUtils-i386.a libGoogleMapsUtils-x86_64.a libGoogleMapsUtils-armv7.a libGoogleMapsUtils-arm64.a 
>     lipo -create -output $@ $^  
> 
> clean:
>     rm -rf ios
> 
> .PHONY: all clean

Then I open the solution file in xamrin studio and build. Build is failed and I got error...

> **/../Google-Maps-Utils-Binding/GoogleMapsUtils.iOS/CSC: Error CS1566: Error reading resource file `extern/libGoogleMapsUtils.a' (CS1566) (GoogleMapsUtils.iOS)**

**Comment by tahmidmozaffar** [comment]
![screen shot 2016-11-03 at 11 46 45 pm](https://cloud.githubusercontent.com/assets/3339156/19978060/d785a2f6-a21f-11e6-8c45-7bda863390e7.png)

**Comment by tahmidmozaffar** [comment]
Ok. Now I made the dll and I understood what I did wrong. I did not run the makefile correctly. Now I have realised that it is just and txt file and i have to run command in terminal using 'make'.  Poor me... :)
