### ISSUE TITLE
Error on building in xamarin studio

### ISSUE THREAD

**Issue by tahmidmozaffar** [NateRickard/Google-Maps-Utils-Binding#4]
Hello, 

I got this error when trying to build the sample project in xamarin studio.
Error CS1566: Error reading resource file `extern/libGoogleMapsUtils.a' (CS1566) (GoogleMapsUtils.iOS)

how can I solve this?

**Comment by nvduc2910** [comment]
yes. I got too. please tell me how fix it

**Comment by tahmidmozaffar** [comment]
Hello, I solved it then. You have to first run the Makefile that is in the extern directory. Then you can build the project. Then you can use the generated .dll file in your project

**Comment by nvduc2910** [comment]
Thank for reply,

I solved this issue by clone HTTPS instead SSH . but I got this error again. can you review my screenshots when run Makefile . I don't know Makefile run success or fails . Thanks.
![screen shot 2017-02-21 at 3 18 37 pm](https://cloud.githubusercontent.com/assets/12984583/23156400/5f7bf38e-f849-11e6-99f1-3a80411abe02.png)

**Comment by tahmidmozaffar** [comment]
You should install CocoaPods first. Then if you run 'make' command in the extern folder this should be working.

To install cocoapods... https://guides.cocoapods.org/using/getting-started.html

**Comment by nvduc2910** [comment]
I have solved this issue. Thank you very much.
